CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(120) DEFAULT 'Admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  slug VARCHAR(50) NOT NULL UNIQUE,
  first_name VARCHAR(50) DEFAULT NULL,
  last_name VARCHAR(50) DEFAULT NULL,
  title VARCHAR(100) DEFAULT NULL,
  company VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  website VARCHAR(255) DEFAULT NULL,
  whatsapp VARCHAR(20) DEFAULT NULL,
  instagram VARCHAR(100) DEFAULT NULL,
  facebook VARCHAR(255) DEFAULT NULL,
  tiktok VARCHAR(255) DEFAULT NULL,
  logo VARCHAR(255) DEFAULT NULL,
  views INT DEFAULT 0,
  taps INT DEFAULT 0,
  scans INT DEFAULT 0,

  bio TEXT NULL,
  location_url VARCHAR(255) DEFAULT NULL,
  package_name VARCHAR(100) DEFAULT 'Starter Digital Card',
  is_active TINYINT(1) DEFAULT 1,
  info_page_enabled TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_info_pages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  card_id INT NOT NULL,
  headline VARCHAR(255) DEFAULT '',
  about TEXT,
  services TEXT,
  opening_hours TEXT,
  gallery_note TEXT,
  cta_text VARCHAR(150) DEFAULT 'WhatsApp Business',
  cta_url VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS card_clicks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  card_id INT NOT NULL,
  click_type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
);